[45기 이수빈] Feature/main function
wecode-bootcamp-korea/45-1st-rgb-frontend pull request #15
Opened 2023-05-08 02:32 UTC by cinematicmoment

---
<br />

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.
- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

> 아트 사이트라는 특징으로 불필요한 요소를 최대한 제거하고 유저가 제품에만 집중할 수 있게  구성하였습니다.
이커머스 웹사이트에서 가장 흔하게 볼 수 있고 그만큼 효과적인 carousel 슬라이더를 사용하여 많은 정보를 
노출 시킬 수 있도록 개발하였습니다.
보여주는 것에서 끝나는 것이 아닌 클릭 했을 때 사이트의 다른 영역에도 접근 할 수 있게 구성하였습니다.
Prev / Next 슬라이드로 이동할 수 있는 컨트롤 버튼을 명확하게 구분지어 구성하였습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

> 유저에게 직관적인 디자인 구성으로 사용자가 콘텐츠를 쉽게 유추하고 탐색할 수 있다.
하나 이상의 컨텐츠를 carousel 구성으로 보여줌으로서 유저의 관심도를 높인다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 그리고 상세 내역을 적어주세요.

carousel 기능
메인 페이지 / 상품 이미지 호버시 애니메이션 (기능 구현예정)

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. (drag & drop 또는 첨부파일 추가)
<br />

![screencapture-localhost-3000-2023-05-08-11_25_29](https://user-images.githubusercontent.com/127685269/236720225-f32676f5-28da-43fb-93e0-3d5fb8e9bbac.png)

(레이아웃 비율 조절 예정)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

-  새로운 배열메서드 filter를 쓸 수 있게됐습니다.
- mockData 와 map 메서드로 반복되는 UI를 그릴 수 있게 되었습니다.
- async/await fetch 함수를 써보긴 했는데 다시 공부해봐야 할 것 같습니다.
- carousel 슬라이드를 만들어 봤는데 다음에는 이미지가 움직이는 넓이 값을 잘 계산해서 구성 해봐야겠습니다.

2023-05-08 07:49 UTC, 14-yoonl requested changes
수고많으셨습니다!
리뷰 반영해주세요

2023-05-08 07:49 UTC, 5yoonl commented on src/components/Cart/Cart.scss
> +  }
모두 같은 css가 적용되어 있네요! 한가지className으로 합칠 수 있겠습니다

2023-05-08 07:49 UTC, 5yoonl commented on src/components/Cart/Cart.scss
> +  }
마찬가지로 한가지 className으로 합칠 수 있어요

2023-05-08 07:49 UTC, 14-yoonl commented on src/components/Login/Login.js
> +    fetch("", {
url이 없는 상태로 올라와있네요?

2023-05-08 07:49 UTC, 14-yoonl commented on src/pages/Main/CarouselItem.scss
> +    // }
사용하지 않는 코드는 삭제해주세요!

2023-05-08 07:49 UTC, 14-yoonl commented on src/pages/Main/MainArtist.scss
> +    }
img 태그를 사용하지 않고 div의 background를 활용하신 이유가 있을까요?

2023-05-08 07:49 UTC, 14-yoonl commented on src/pages/Main/MainArtistNext.scss
> +@import "../../styles/mixin";
2개중에 하나는 안쓰이네요! 안쓰이는 부분은 삭제 or 활용할 수 있는 부분 찾아서 활용해주세요

2023-05-08 07:49 UTC, 14-yoonl commented on src/pages/Main/MainCarousel.js
> +    })
fetch 함수의 기본 동작은 GET 요청입니다!
함수에 희망하는 동작이 get 요청이면 method를 생략해도 무관합니다! 이 부분은 참고만 하고 수정은 하지 않으셔도 괜찮습니다!

2023-05-08 07:49 UTC, 14-yoonl commented on src/pages/Main/MainCarousel.js
> +    }
ref를 활용하는김에 buttonNext와 prev에도 ref를 달아서 구현해보시는건 어떨까요?

2023-05-08 09:24 UTC, cinematicmoment commented on src/components/Login/Login.js
> +    fetch("", {
이건 수정님 로그인 페이지 입니다!

2023-05-08 09:25 UTC, cinematicmoment commented on src/pages/Main/MainArtist.scss
> +    }
배경화면이라 background 활용했습니다!

2023-05-09 01:24 UTC, 14-yoonl approved these changes
```jsx
⭐️⭐️⭐️⭐️
⭐️LGTM⭐️
⭐️⭐️⭐️⭐️
```

2023-05-09 01:25 UTC, merged