[45기 문유현] Feature/order layout
wecode-bootcamp-korea/45-1st-rgb-frontend pull request #5
Opened 2023-05-04 14:00 UTC by yoohmoon

수고하셨습니다. 다음은 프로젝트에서 구현한 내용의 기획, 의도, 기대효과를 작성하는 PR 양식입니다.

아래 내용을 참고하셔서 각 브랜치별 PR을 꼭 꼼꼼히 작성하여 올려주세요!

- **"(예시)"** 라고 되어있는 부분은 삭제해주시고 개인 작성 내용만 남겨서 기록해주세요.
<br />

---

<br />

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.
- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?
-  주문 과정이 길게 느껴지지 않도록 배송 정보 입력 단계와 결제 방법 선택 단계를 나누어 화면에 보여주어 유저의 이탈을 방지한다. 

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
- 기본 배송지로 설정하는 옵션을 줌으로써 사용자가 일일이 배송지를 입력해야하는 수고를 덜어 유저 전환의 허들을 낮출 수 있다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 그리고 상세 내역을 적어주세요.
- 주문 페이지를 배송지 정보 입력 부분, 결제 방법 부분으로 나누어 레이아웃을 개발했습니다.

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. (drag & drop 또는 첨부파일 추가)
![image](https://user-images.githubusercontent.com/121086010/236230034-2d35d977-006b-4ed8-b7e2-f4ee82a40dbc.png)
![image](https://user-images.githubusercontent.com/121086010/236230168-845c82b2-4d8a-4e06-aaa3-f717ade36882.png)

<br />

-

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.
- 컴포넌트를 분리하여 작은 단위로 레이아웃을 구성하는 것을 다시 복습할 수 있었습니다.
- input checkbox 태그 사용을 통한 레이아웃 구성을 복습할 수 있었습니다.

  <br />

2023-05-04 14:29 UTC, 14-yoonl reviewed
수고 많으셨습니다 ! 리뷰내용 반영해주세요~

2023-05-04 14:29 UTC, 14-yoonl commented on src/pages/Order/Order.js
> +        <Payment />
Delivery와 Payment 컴포넌트가 조건에 따라 랜더링되는부분인것 같습니다. 당장에 주석처리한 부분은 필요없어 보이니  주석은 삭제해주세요!

2023-05-04 14:29 UTC, 14-yoonl commented on src/pages/Order/Order.scss
> +}
className이 order인 div의 네스팅이 여기서 닫혀버리네요!
하위에 있는속성들이 정상적으로 적용되는것에는 문제가 없어보이나 nesting규칙에 맞게끔 수정해주세요

2023-05-04 14:29 UTC, 14-yoonl commented on src/pages/Order/Order.scss
> +  }
leftArrow 보단 goBackArrow등 동작을 나타내는 className이 더 적절해보입니다

2023-05-04 14:29 UTC, 14-yoonl commented on src/pages/Order/components/OrderList/OrderList.js
> +        </div>
같은 내용이 반복되고있습니다! 내용을 상수데이터로 관리하고 반복문 사용해줄 수 있겠네요!

2023-05-04 14:29 UTC, 14-yoonl commented on src/pages/Order/components/Payment/Payment.js
> +import Button from "../../../../components/Button/Button";
필수적인 내용은 아니지만  컴포넌트 - css 파일  등 import해오는 파일들도 종류별로 정리해주시면 가독성에 더 도움이 되겠습니다!

2023-05-04 14:29 UTC, 14-yoonl commented on src/pages/Order/components/Payment/Payment.js
> +          </div>
아까 질문 주셨던 부분이네요! 상수데이터로 관리후 반복문 메서드 활용해주시면 좋겠습니다!

2023-05-08 11:53 UTC, yoohmoon commented on src/pages/Order/components/OrderList/OrderList.js
> +        </div>
`  <ul className="orderItem">
            <li>합계</li>
            <li>₩{totalPriceComma}</li>
          </ul>`

{totalPriceComma}와 같이 동적인 값도 상수데이터로 관리 후, map을 사용할 수 있나요?

2023-05-08 13:07 UTC, 14-yoonl requested changes
수고하셨습니다 유현님!
아직 기능구현을 위해 사용한 임의의 코드가 pr에 많이 남아있습니다 
ex) 하드 코딩된 영역, 콘솔, 주석등등
리뷰 요청 전에 본인의 pr을 확인 하셔서 콘솔 및 주석과 같은 기능개발을 위한 테스트 코드가 남아있지는 않는지 확인하는 습관을 길러주시면 좋겠습니다

2023-05-08 13:07 UTC, 14-yoonl commented on src/pages/Order/Order.js
> +  };
이 부분은 정일님이 말씀해주신 reduce 사용하지 않고 이렇게 진행하시는건가요?

2023-05-08 13:07 UTC, 14-yoonl commented on src/pages/Order/Order.js
> +      },
기능테스트 끝나셨으면 하드코딩이 아닌 실제 localStorage에서 토큰 가져오는 로직도 추가해주세요!

2023-05-08 13:07 UTC, 14-yoonl commented on src/pages/Order/Order.js
> +  console.log("⚙️", totalPrice);
콘솔 삭제해주세요!

2023-05-08 13:07 UTC, 14-yoonl commented on src/pages/Order/components/Delivery/Delivery.js
> +  };
주석 없어도 충분히 이해할 수 있는 코드 함수들 입니다 주석은 삭제 해주세요!

2023-05-08 13:07 UTC, 14-yoonl commented on src/pages/Order/components/OrderHeader/OrderHeader.js
> +  // console.log("isDelivery 상태값? ", isDelivery);
사용하지 않는 주석은 삭제해주세요!

2023-05-08 13:07 UTC, 14-yoonl commented on src/pages/Order/components/Payment/Payment.js
> +      // JSON.stringify({ userId: userData.id, products: orderedProductsArr }),
여기도 주석 삭제해주세요

2023-05-10 04:54 UTC, 14-yoonl approved these changes
수고하셨습니다 유현님!
코드의 가독성을 위해서 변수선언, state선언, 함수선언을 좀 더 보기 좋게 정렬하는 습관을 들이시면 좋겠습니다.

2023-05-10 04:55 UTC, merged